name: Віддалений деплоймент

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Середовище для деплойменту'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Деплоймент на сервер
    
    steps:
    - name: Підключення до сервера і оновлення коду
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT || 22 }}
        script: |
          echo "🚀 Початок деплойменту..."
          
          # Перехід до каталогу httpdocs
          cd httpdocs
          
          # Показуємо поточну гілку
          echo "📂 Поточна гілка:"
          git branch --show-current
          
          # Показуємо статус перед оновленням
          echo "📊 Статус репозиторію перед оновленням:"
          git status --porcelain
          
          # Перевіряємо чи є локальні зміни і пушимо їх перед pull
          if [ -n "$(git status --porcelain)" ]; then
            echo "⚠️ Знайдено локальні зміни (можливо автооновлення WordPress)"
            echo "💾 Додаємо зміни до репозиторію..."
            git add .
            git commit -m "Auto-commit: локальні зміни перед деплойментом $(date +'%Y-%m-%d %H:%M:%S')"
            echo "⬆️ Пушимо зміни в репозиторій..."
            git push origin main
          else
            echo "✅ Локальних змін немає"
          fi
          
          # Виконуємо git pull
          echo "⬇️ Завантаження останніх змін..."
          git pull origin main
          
          # Показуємо останній коміт
          echo "✅ Останній коміт:"
          git log -1 --oneline
          
          echo "🎉 Деплоймент завершено успішно!"
          
    - name: Повідомлення про результат
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Деплоймент успішно завершено!"
        else
          echo "❌ Деплоймент завершився з помилкою!"
        fi 